Traceback (most recent call last):
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/bin/cutadapt", line 10, in <module>
    sys.exit(main())
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/__main__.py", line 855, in main
    stats = r.run()
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/pipeline.py", line 645, in __exit__
    self.close()
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/pipeline.py", line 821, in close
    self._pipeline.close()
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/cutadapt/pipeline.py", line 210, in close
    self._reader.close()
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/dnaio/readers.py", line 35, in close
    self._file.close()
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/xopen/__init__.py", line 236, in close
    self._raise_if_error(allow_sigterm=allow_sigterm)
  File "/exports/csce/eddie/biology/groups/wallace_rna/anaconda/envs/riboviz/lib/python3.7/site-packages/xopen/__init__.py", line 259, in _raise_if_error
    raise OSError("{} (exit code {})".format(message, retcode))
OSError: pigz: /exports/igmm/software/pkg/el7/apps/hdf5/1.8.16/lib/libz.so.1: version `ZLIB_1.2.5.1' not found (required by pigz) (exit code 1)
